// <auto-generated />
using System;
using DeliveryProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416184315_deliveryDB")]
    partial class deliveryDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliveryProject.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ClientID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DeliveryProject.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DriverID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.HasIndex("VehicleID");

                    b.HasIndex("ZoneID");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DeliveryProject.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("ClientID");

                    b.HasIndex("ShipmentID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DeliveryProject.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DeliveryProject.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ShipmentId");

                    b.HasIndex("ClientID");

                    b.HasIndex("DriverID");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("DeliveryProject.Models.ShipmentStatus", b =>
                {
                    b.Property<int>("ShipmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("StatusValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ShipmentID");

                    b.ToTable("ShipmentStatus");
                });

            modelBuilder.Entity("DeliveryProject.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeliveryProject.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"));

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleID");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DeliveryProject.Models.Zone", b =>
                {
                    b.Property<int>("ZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZoneID");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("DeliveryProject.Models.Client", b =>
                {
                    b.HasOne("DeliveryProject.Models.User", "user")
                        .WithOne("client")
                        .HasForeignKey("DeliveryProject.Models.Client", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("DeliveryProject.Models.Driver", b =>
                {
                    b.HasOne("DeliveryProject.Models.User", "user")
                        .WithOne("driver")
                        .HasForeignKey("DeliveryProject.Models.Driver", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryProject.Models.Vehicle", "vehicle")
                        .WithMany("drivers")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryProject.Models.Zone", "zone")
                        .WithMany("drivers")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");

                    b.Navigation("vehicle");

                    b.Navigation("zone");
                });

            modelBuilder.Entity("DeliveryProject.Models.Payment", b =>
                {
                    b.HasOne("DeliveryProject.Models.Client", "client")
                        .WithMany("payments")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryProject.Models.Shipment", "shipment")
                        .WithOne("payment")
                        .HasForeignKey("DeliveryProject.Models.Payment", "ShipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("shipment");
                });

            modelBuilder.Entity("DeliveryProject.Models.Shipment", b =>
                {
                    b.HasOne("DeliveryProject.Models.Client", "client")
                        .WithMany("shipments")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliveryProject.Models.Driver", "driver")
                        .WithMany("shipments")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("driver");
                });

            modelBuilder.Entity("DeliveryProject.Models.ShipmentStatus", b =>
                {
                    b.HasOne("DeliveryProject.Models.Shipment", "shipment")
                        .WithMany("shipmentStatuses")
                        .HasForeignKey("ShipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shipment");
                });

            modelBuilder.Entity("DeliveryProject.Models.User", b =>
                {
                    b.HasOne("DeliveryProject.Models.Role", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("DeliveryProject.Models.Client", b =>
                {
                    b.Navigation("payments");

                    b.Navigation("shipments");
                });

            modelBuilder.Entity("DeliveryProject.Models.Driver", b =>
                {
                    b.Navigation("shipments");
                });

            modelBuilder.Entity("DeliveryProject.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DeliveryProject.Models.Shipment", b =>
                {
                    b.Navigation("payment")
                        .IsRequired();

                    b.Navigation("shipmentStatuses");
                });

            modelBuilder.Entity("DeliveryProject.Models.User", b =>
                {
                    b.Navigation("client");

                    b.Navigation("driver");
                });

            modelBuilder.Entity("DeliveryProject.Models.Vehicle", b =>
                {
                    b.Navigation("drivers");
                });

            modelBuilder.Entity("DeliveryProject.Models.Zone", b =>
                {
                    b.Navigation("drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
